### ISSUE TITLE
命令不一致问题

### ISSUE THREAD

**Issue by WasserWelt** [FAS-Server/CarpetBotManager#10]
在使用`!!player <bot> <动作>`命令，为bot添加预设动作成功后，于`!!bot list`界面中点击执行，填充命令`!!bot action <bot> exec`，返回未知参数。检查后发现，正确命令为`!!bot actions`，该错误在许多地方都有出现。

**Comment by 401U** [comment]
在提交 32164a 中，更新命令实现时，错误地将命令参数改成了actions🤔会尽快修复
