### ISSUE TITLE
!!bot kill bot_<name> throw Can only manipulate existing players

### ISSUE THREAD

**Issue by vcup** [FAS-Server/CarpetBotManager#3]
嗯我不是很会英语就不那么国际化了
插件可以正常召唤假人，但如果想要假人下线的话carpet会说只能下线已有玩家
翻到源码发现到是在这里执行地毯的命令，于是在这里加了个reply，把self.name回显给玩家。
https://github.com/FAS-Server/CarpetBotManager/blob/0b22c3c34a4a0ca6620bf02b408197766354351d/carpet_bot_manager/bot.py#L93-L95
发现在这里，self.name的值是bot_\<name\>，然而插件召出来的假人的名称只有一个\<name\>

我不是很明白为什么会出现这种问题的？

**Comment by 401U** [comment]
这里是对`carpet-tis-addition`中自动添加假人名称前后缀功能的支持，不需要可以修改相应配置文件

**Comment by vcup** [comment]
> 这里是对`carpet-tis-addition`中自动添加假人名称前后缀功能的支持，不需要可以修改相应配置文件

了解了，不过对于这样的支持不是应该默认关闭的吗？似乎在`carpet-tis-addition`中也是默认不加前后缀的
https://github.com/TISUnion/Carpet-TIS-Addition/blob/master/docs/rules.md#fakeplayernameprefix
在这里，它的默认值是#none

**Comment by 401U** [comment]
已修改相关默认配置项
