### ISSUE TITLE
Adding a bot doesn't work

### ISSUE THREAD

**Issue by Power-tile** [FAS-Server/CarpetBotManager#4]
Running `!!player <name> spawn <x> <y> <z> facing <pitch> <yaw> in <dim_id>` says that this feature is still in dev. Adding the bot info manually in the config file according to `README.md` + running `!!MCDR reload all` does not add the bot to the `!!bot list` output. How can I add a bot?

**Comment by 401U** [comment]
Currently you can use `!!player <name> spawn` to add an bot at your position, which is the only way to add bot now

**Comment by 401U** [comment]
#2
