### ISSUE TITLE
Kicking a bot does not work

### ISSUE THREAD

**Issue by waynezhao12** [FAS-Server/CarpetBotManager#5]
I tried to use the kick button in `!!bot list` panel to kick a bot, but it shows '[Server: Can only manipulate existing players]'
![image](https://user-images.githubusercontent.com/8773195/151699234-e7ff5fc4-ebad-4e20-b190-521f55a647cf.png)
I'm pretty sure the bot is existing. Could you help me to solve this?

**Comment by 401U** [comment]
Can you give some detailed info, such as plugin config and weather you used the fake player prefix/suffix in carpet-tis-addition?

**Comment by waynezhao12** [comment]
Plugin configs are as follow. I'm basically using the default setting
```json
{
    "debug": false,
    "bots": {
        "bot_gr_h": {
            "desc": "Nothing here.",
            "pos": [
                -514.4497861639503,
                63.0,
                -164.30000001192093
            ],
            "dim": 0,
            "rotation": [
                174.89783,
                28.500128
            ],
            "actions": []
        }
    },
    "name_prefix": "bot_",
    "name_suffix": "",
    "page_len": 15
}
```

The prefix and suffix functions in carpet-tis-addition are set to #none

**Comment by 401U** [comment]
>     "name_prefix": "bot_",
Set this with empty, like "", as you set #none in carpet-tis-addition
will update readme later

**Comment by waynezhao12** [comment]
It works. Thank you!
